# Generated by Django 3.1.2 on 2020-11-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='ano_de_egreso',
            new_name='egreso',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='ano_de_ingreso',
            new_name='ingreso',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='calificador_anual',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='dni',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='trayectoria',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
