# Generated by Django 3.1.2 on 2020-11-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0002_auto_20201102_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='calificador_anual',
            new_name='calif_anual',
        ),
        migrations.AddField(
            model_name='alumno',
            name='doc_ingreso',
            field=models.CharField(blank=True, choices=[('Certificado de 7mo', 'Certificado de 7mo'), ('Constancia de Alumno Regular', 'Constancia de Alumno Regular'), ('Analítico Parcial', 'Analítico Parcial')], max_length=64),
        ),
    ]
