# Generated by Django 3.1.2 on 2020-11-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0004_auto_20201104_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Secretaria/o', 'Secretaria/o'), ('Preceptor/a', 'Preceptor/a')], default='preceptor', max_length=64),
        ),
    ]
