# Generated by Django 3.1.2 on 2020-11-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0005_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Secretaria/o', 'Secretaria/o'), ('Preceptor/a', 'Preceptor/a')], default='Preceptor/a', max_length=64),
        ),
    ]
