# Generated by Django 3.1.2 on 2020-11-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0006_auto_20201106_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='es_egresado',
            field=models.BooleanField(default=False),
        ),
    ]
