# Generated by Django 3.1.2 on 2020-11-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0012_auto_20201107_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='disposicion',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
