# Generated by Django 3.1.2 on 2020-11-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0013_auto_20201110_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='disposicion',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
