# Generated by Django 3.1.2 on 2020-11-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0016_auto_20201110_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='es_egresado',
        ),
        migrations.AddField(
            model_name='alumno',
            name='tipo',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Egresado/a', 'Egresado/a'), ('Salido con pase', 'Salido/a con pase'), ('Salido sin pase', 'Salido/a sin pase')], default='Activo', max_length=64),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='doc_ingreso',
            field=models.CharField(blank=True, choices=[('Certificado de 7mo', 'Certificado de 7mo'), ('Constancia de materias aprobadas', 'Constancia de materias aprobadas'), ('Analítico parcial', 'Analítico parcial')], max_length=64),
        ),
    ]
