# Generated by Django 3.1.2 on 2020-11-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0018_auto_20201111_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='tipo',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Egresado/a', 'Egresado/a'), ('Salido con pase', 'Salido/a con pase'), ('Salido sin pase', 'Salido/a sin pase')], default='Activo', max_length=64),
        ),
    ]
