# Generated by Django 3.1.2 on 2020-11-11 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0020_auto_20201111_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='tipo',
            new_name='condicion',
        ),
    ]
