# Generated by Django 3.1.2 on 2020-11-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0021_auto_20201111_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='fecha_pase_confeccionado',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='alumno',
            name='fecha_pase_legalizado',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='alumno',
            name='fecha_titulo_confeccionado',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='alumno',
            name='fecha_titulo_legalizado',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='alumno',
            name='fecha_titulo_retirado',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='alumno',
            name='pase_confeccionado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumno',
            name='pase_legalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumno',
            name='titulo_confeccionado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumno',
            name='titulo_legalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumno',
            name='titulo_retirado',
            field=models.BooleanField(default=False),
        ),
    ]
